services:
  jacksonii_base:
    image: jacksonii_analyses:latest
    container_name: jacksonii_analyses
    volumes:
      - ${PWD}:/workspace
      - ${DATA_PATH:-$PWD/data}:/workspace/data
    environment:
      - PYTHONPATH=/opt/conda/lib/python3.12/site-packages
    working_dir: /workspace
    #user: "${UID:-1000}:${GID:-1000}"
    command: tail -f /dev/null
